# Generated by Django 4.2 on 2023-04-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='review_post',
            field=models.TextField(blank=None, null=True),
        ),
    ]
