# Generated by Django 4.2 on 2023-04-29 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store_books', '0005_userbookrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.ManyToManyField(through='store_books.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='author_review_post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
